### ISSUE TITLE
CAS logout

### ISSUE THREAD

**Issue by joshAppDev** [digi-serve/ab_platform_web#126]
**Describe the bug**
After logging out under CAS auth, we are shown a local auth login screen. And if we reload the page, we get logged in again automatically without needing to enter any credentials. This is because the session with the CAS server still remains active.

**To Reproduce**
1. Login to a CAS enabled site
2. Click on the user icon in the top right, and select `Logout`.
3. The local auth login screen will be shown.
4. Refresh the web page.

**Expected behavior**
When logging out under CAS, the site should redirect the user to https://[cas server]/cas/logout?service=[AB tenant site url]
This will end the session with the CAS server and prevent an immediate re-login.

**Server**
staging2

**Additional context**
When CAS is enabled, there should be these server side config settings:
```js
sails.config.cas.enabled == true;
sails.config.cas.baseURL == "https://signin.example.com/cas";
```

The AppBuilder tenant site URL can be found in the `site_tenant` table, under the `properties` column. 
```json
{ "title":"Tenant Admin", "authType":"cas", "url":"https://staging2.appdevdesigns.net" }
```

I tried to fix this myself, but I could not find the code that controls the UI logout link. Sorry.

**Comment by jamesduncan** [comment]
As I was working on this I was attempting to read the values of in the Tenant's options with the provided method of AB.Tenant.setting(key) but it never returned anything. I discovered that the options were stored as a string so the method would never return a value. This fix should allow us to get the proper value back going forward. I don't know if this will fix the logout issue but it is the first step because I will need to properly get the "url" of the tenant to build the logout link at some point.

**Comment by jamesduncan** [comment]
I am going to assign this to Pong and once he and Joshua can approve/deny the PR we can test to see if just this small change makes a difference for the logout...if it doesn't we will at least have the tools we need to write the change here...
https://github.com/digi-serve/ab_service_api_sails/blob/master/api/controllers/auth/logout.js#L25
I believe the new code will be something like 
```
   // passport session logout feature:
   if (req.logout) {
      if (sails.config.cas.enabled) {
         req.logout(req, res, `${sails.config.cas.baseURL}/logout?service=${this.AB.Tenant.setting("url")}`);
      } else {
         req.logout();
      }
   }
```

**Comment by joshAppDev** [comment]
That looks good to me. There's also the matter of how the AB front end responds to the logout. From what I can tell, when you click to logout, it does a `POST /auth/logout`. So when the logout.js controller handles the server side logic for that, the front end may need additional changes to redirect the main window to the CAS logout page.

**Comment by jamesduncan** [comment]
Okay I have a couple pull requests that hopefully will work for us. First just passes the tenant url to the logout in the change we need it. The second checks if we are using cas and if so calls the cass logout (which in the end also calls the regular logout to ensure we logged out of the site as well as CAS).

https://github.com/digi-serve/ab_platform_web/pull/144
https://github.com/digi-serve/ab_service_api_sails/pull/22

**Comment by jamesduncan** [comment]
I have made the changes needed to get the CAS logout to work...but to your point above I may need to do more work to get the front end to behave as we expect. Let's see where this gets us first.

**Comment by jamesduncan** [comment]
Okay...my attempt to use CasStrategy didn't work out so I am just doing the redirect to the logout url. Hopefully this will work for us...not sure still if the page will eventually make it back to a CAS login but we will see.

**Comment by jamesduncan** [comment]
https://github.com/digi-serve/ab_service_api_sails/pull/25

**Comment by jamesduncan** [comment]
This needs to be tested but until we can get the code out that fails the tests we cannot release any more code.

**Comment by jamesduncan** [comment]
I was finally able to test the logout logic and it seems to be working as we expect. @wei9528 can you take a look please?

**Comment by wei9528** [comment]
Yes, it's fixed, logout is working. Thanks!
