### ISSUE TITLE
Forms not loading default cursor's data.

### ISSUE THREAD

**Issue by jamesduncan** [digi-serve/ab_platform_web#251]
It looks like the default data is loading over the top of a default cursor. If you lower the timeout it seems to work...but I don't know if that is a good fix.

https://github.com/digi-serve/ab_platform_web/blob/67bdf39d359a5b6b3647ae6ffd714a270e676c16/AppBuilder/platform/views/viewComponent/ABViewFormComponent.js#L389

**Comment by jamesduncan** [comment]
The easiest way to check this is to load the Kitchen Sink app and then click on the "Combo" tab. The form at the top should have values set and visible.

What you see now.
<img width="1318" alt="Screen Shot 2023-02-24 at 1 45 27 PM" src="https://user-images.githubusercontent.com/106924/221110728-eb327bc3-10df-486e-a0a4-8f3f5b12e1b8.png">

What you should see.
<img width="1317" alt="Screen Shot 2023-02-24 at 1 45 34 PM" src="https://user-images.githubusercontent.com/106924/221110768-6a96ef16-c4b0-4266-86d2-c5b81a41793a.png">

**Comment by jamesduncan** [comment]
I added you guys to this ticket so you can let me know what you think. A possible fix could be to lower the time...or perhaps handle the "setting of defaults" differently so it doesn't reset values that are already set.

**Comment by wongpratan** [comment]
Do we need `await timeout(80);` in `.displayData` function?

If yes, Should we update what functions call `.displayData` to be `async` ?
