### ISSUE TITLE
Filter Data Collection by another Data Collections Cursor

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_platform_web#279]
Use Case:
To improve performance loading data collections with many connections.
Use a Data Collection "A" without populate for the Grid. Use Data Collection "B" with populate based on the cursor of "A" for Detail.

### Requirements

- Data Collections can select to follow the cursor of another Data Collection (with the same base object).
- If selected hide normal data collection filters, cursor fix etc.
- Listen to cursor changes on the followed dc, only load that record
- Always select the first (only) record.

### Details

![Image](https://user-images.githubusercontent.com/10155226/229688930-8d514e55-b00a-42be-be5a-8d42ff296779.png)

https://snippet.webix.com/nrdhgvhv

**Comment by Achoobert** [comment]
When feature is useable, I can throw together a test for it.
