### ISSUE TITLE
Add new Error message due to missing required field in Global HR Web app

### ISSUE THREAD

**Issue by Achoobert** [digi-serve/ab_platform_web#292]

**Comment by Achoobert** [comment]
It would be fantastic to see a better "send message to user" tool

I'm needing one for the AB Designer versioning system, to help notify Builders

**Comment by joshAppDev** [comment]
There are two changes to the Global HR web app:
1. If approving a form gets an error from Netsuiite, the error message should now be shown on screen.
2. We are now sending data to Netsuite in a way that bypasses some of the required field restrictions. So the error should not even come up anymore.
