### ISSUE TITLE
Error loading datacollections

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_platform_web#32]
**Describe the bug**
Data does not load, error seen in console.

**To Reproduce**
1. Import kitchen-sink app into v2
2. Reload and check the console (see error)
3. Go to the grid tab (see loading spinner)

**Expected behavior**
Data should load, no error in console

**Screenshots**
![image](https://user-images.githubusercontent.com/10155226/145552815-c092e754-605d-4c93-8265-2307f11c9cf0.png)

**Additional context**
`localhost/:1 Uncaught (in promise) {status: 'error', data: {…}, message: "TypeError: Cannot read properties of undefined (reading 'raw')"}`

**Comment by jamesduncan** [comment]
In the instructions there are steps to install the app but no steps to insert sample data into the app. Therefore if there is no data there is nothing to load into the grid. Perhaps this bug is just that the loader does not go away when there are 0 results returned?
