### ISSUE TITLE
Research Slow Network warning

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_platform_web#436]
Sites like youtube/gmail can detect when a network is slow. 
This could help communicate to users when the performance is slow due to network conditions.

## Requirements
- Research and propose a method to detect

## Reference 
Does not include implementing
Maybe we could build on  Network Latency tests? https://team.digiserve.org/main/pl/wzheem1jt3d97qmrrecn7iqjkr

**Comment by zachhh3** [comment]
Have the user download a tiny image multiple times, generating average download speed. Set a threshold value (e.g > 150ms) that determines what is slow. 

On very very slow networks, test may take some time to complete which could hog bandwidth.  We can write a _setTimeout_ within the function to terminate if the image wasn't downloaded in _threshold*3_ (some arbitrary number) and consider it as slow network.

https://github.com/Saunved/isfastnet
