### ISSUE TITLE
Cannot Change from English to Thai Language on Design Server

### ISSUE THREAD

**Issue by Tacchinardi20** [digi-serve/ab_platform_web#463]
**Describe the bug**
On design server, there was nothing happened when we chose and clicked on Thai language of User Profile Setting and then refreshed. After refresh, I had checked on the User Profile Setting. On Language title was still English language the same.

**To Reproduce**
1. Go to top right corner 'User Profile'
2. Click on 'Language' and choose Thai language
3. Refresh the site, this should see a change.

**Screenshots**
![image](https://github.com/digi-serve/ab_platform_web/assets/98794744/6837d045-ccd3-4854-92f5-774a074436aa)

**Server**
Design Server
https://design.digiserve.org

**Comment by nh758** [comment]
There is a good chance this will be fixed by https://github.com/digi-serve/ab_service_api_sails/pull/141. We should wait for that to merge and then test further.

**Comment by Tacchinardi20** [comment]
After I restart the server, the site has auto changed to Thai language which I can't change it back to English language.

**Comment by jamesduncan** [comment]
If you reload without cache it seems to work. Do we need to invalidate the cached settings after a user changes their language so the app knows to download new settings?

**Comment by nh758** [comment]
Fixed in `appbuilder v1.1.4`, `user_manager v1.1.4` and `tenant_manager v1.1.3`
