### ISSUE TITLE
Saving Connected Field Values Bug

### ISSUE THREAD

**Issue by jamesduncan** [digi-serve/ab_platform_web#509]
**Describe the bug**
When you add new connected records to an existing record the previous values are lost.

https://github.com/digi-serve/ab_platform_web/assets/106924/aac25d2e-d3b2-4c09-8f5b-f28879ae317d

**Server**
Seen on design.digiserve.org

**Comment by jamesduncan** [comment]
This bug seems to occur when you make no changes as well and just click save. All previous selected records are removed.


https://github.com/digi-serve/ab_platform_web/assets/106924/6c212042-2002-4c26-a503-1be32690fc43

**Comment by jamesduncan** [comment]
I am going to set up a small application that tests this bug to make sure it isn't just an isolated issue with this particular form/object/app.

**Comment by jamesduncan** [comment]
Here is the line that needs to be changed.

https://github.com/digi-serve/ab_platform_web/commit/e695f0ef37036b1b069b9217ab24c67ad8eec04e#r141591416

I am not sure if Line: 801 needs the same change though.

**Comment by Hiro-Nakamura** [comment]
### Good Catch!

OK, I was questioning why line `801` doesn't need to change, but realized in the code, that `option.forUpdate` is only considered if the link is a `many:*` relationship. `801` wouldn't get used in that type of relationship so the rest of that fn works with/or without the `option.forUpdate`.

This is a big enough bug that I would like to see your test code make its way into the `kitchensink` app.  Those previous changes sailed right through there without notice.  So we need to add this case into our testing.
