### ISSUE TITLE
Add new option for "Is Current Date" to filter a DataCollection by one of it's date fields

### ISSUE THREAD

**Issue by jamesduncan** [digi-serve/ab_platform_web#511]
**Is this related to a problem?**
Indy needs this feature for the Clinic application he is working on right now.

**Desired Solution**
Add an option in the filters for "Is Current Date". We currently have before and after options so it shouldn't be too difficult to support this case.

<img width="485" alt="Screenshot 2024-05-02 at 3 32 15 PM" src="https://github.com/digi-serve/ab_platform_web/assets/106924/c3b90933-d40a-4d3f-b70c-51f413b31938">

**Comment by wirachot** [comment]
On filter "Date type" works fine.  But "datetime type" is not working, I checked on the data collected in the database and it is not the same show on web. Is it problem about timezone on local machine?
![1715336651058](https://github.com/digi-serve/ab_platform_web/assets/6814471/b60f9942-44a1-48a9-8324-1e24a7b14da5)
![screenshot-localhost_8080-2024 05 10-17_23_02](https://github.com/digi-serve/ab_platform_web/assets/6814471/354cc7dd-97ba-48f9-bb75-f02692c6a350)

**Comment by nh758** [comment]
Yes, that looks like different time zones between the client and server. This might be related to https://github.com/digi-serve/ab_platform_web/issues/508

**Comment by wirachot** [comment]
![Image](https://github.com/digi-serve/ab_platform_web/assets/6814471/ee0ae2e1-a851-46a7-bb30-00b4655919f1)

I found some issues when clicked datetime in the form. it's shows a datepicker for a date only. may need to fix this too.
