### ISSUE TITLE
Forgot Password Links Broken

### ISSUE THREAD

**Issue by jamesduncan** [digi-serve/ab_platform_web#555]
**Describe the bug**
When you click on the link from the email sent to reset your password it just shows the login UI and not the reset password UI.

**To Reproduce**
1. Fill out forgot password form.
2. Click on link in email sent to your inbox.

**Expected behavior**
Should see the two password fields to set up a new password.

**Screenshots**

**Server**
https://fcf.childatrisk.in.th/ (all childatrisk sites)

**Comment by nh758** [comment]
Thanks, there were a few changes we made over the past year that each would have broken this. So this probably hasn't been working for a while. Will add tests around this.

**Comment by nh758** [comment]
Fixed in [api_sails v2.1.5](https://github.com/digi-serve/ab_service_api_sails/releases/tag/v2.1.5) and [service_web v1.0.140](https://github.com/digi-serve/ab_service_web/releases/tag/v1.0.140%2Bd10220.p10804.c20213)
